fos_oauth_server:
  db_driver: orm
  client_class:        App\Entity\OAuth2\Client
  access_token_class:  App\Entity\OAuth2\AccessToken
  refresh_token_class: App\Entity\OAuth2\RefreshToken
  auth_code_class:     App\Entity\OAuth2\AuthCode

  service:
    user_provider: App\Security\UserProvider
    options:
      supported_scopes: scope1